/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/PartySupportChart copy.vue')['default']
    Dropdown: typeof import('./src/components/dropdown.vue')['default']
    DropdownComponent: typeof import('./src/components/DropdownComponent.vue')['default']
    PartySupportChart: typeof import('./src/components/PartySupportChart.vue')['default']
    PresidentialVoterTurnoutChart: typeof import('./src/components/PresidentialVoterTurnoutChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestChart: typeof import('./src/components/TestChart.vue')['default']
    VoteRateChart: typeof import('./src/components/VoteRateChart.vue')['default']
  }
}
